-- Supprimer les anciennes séquences (Spring Batch 4/5)
DROP SEQUENCE IF EXISTS BATCH_STEP_EXECUTION_SEQ CASCADE;
DROP SEQUENCE IF EXISTS BATCH_JOB_EXECUTION_SEQ CASCADE;
DROP SEQUENCE IF EXISTS BATCH_JOB_SEQ CASCADE;

-- Supprimer les tables dans l'ordre de dépendance
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT CASCADE;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE CASCADE;

-- Optionnel : Supprimer la table schemas version si elle existe (flyway ?)
-- DROP TABLE IF EXISTS "flyway_schema_history";
